version: 1

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
  file:
    class: logging.FileHandler
    filename: app.log
    formatter: simple

root:
  level: INFO
  handlers: [console, file]

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"