_target_: src.incontextlearner.datamodules.ICLDataModule

train_context:
  size: 100
  label_ratio: random # ["balanced", "random"] or [0, 1]
  minority_ratio: random # ["balanced", "random"] or [0, 1]

val_context:
  size: 100
  label_ratio: random # ["balanced", "random"] or int
  minority_ratio: random # ["balanced", "random"] or int

test_context:
  size: 100
  label_ratio: 0.5 # ["balanced", "random"] or int
  minority_ratio: 0.5 # ["balanced", "random"] or int

batch_size: 64
num_workers: 8

num_classes: ${experiment_settings.embedding_extractor.datamodule.num_classes}
num_confounders: ${experiment_settings.embedding_extractor.datamodule.num_confounders}

cache_path: ${experiment_settings.embedding_extractor.cache_path}