model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  save_top_k: 0 # save k best models (determined by above metric) | if -1, all models are saved.
  save_last: True # additionally, always save model from last epoch
  verbose: False
  dirpath: checkpoints/
  filename: epoch_{epoch:04d}
  auto_insert_metric_name: False