name: compute_encodings_avg_norm_and_generate_tokens
seed: 0
print_config: True
ignore_warnings: False

dataset: inaturalist2017
data_path: ${oc.env:DATA_ROOT_DIR}/${dataset}
encoding_extractor: dinov2_vitb14 # Options: dinov2_vitb14, resnet50
split: null # e.g. for waterbirds you can set 'val'

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/runs/${name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True
