name: compute_encodings_avg_norm_and_generate_tokens
seed: 0
print_config: True
ignore_warnings: False

data_path: ${oc.env:DATA_ROOT_DIR}/inaturalist2017
encoding_extractor: dinov2_vitb14

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/runs/${name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True
