name: evaluate
seed: 0
print_config: True
ignore_warnings: False

spurious_setting: separate_token # Options: 'separate_token'(x,c) , 'no_spurious'(x), 'sum'(x+c), 'sum_with_spurious'(x+c,c)
v1_behavior: False  # True of False should have no effect, because we throw intermediate predictions
aim_hash: 8a1fd0f86cc14ba888bce608  # 50 context_class_size v2, 1000 rotations, sum_with_spurious
checkpoint_path: ${oc.env:OUTPUT_DIR}/runs/train/${aim_hash}/checkpoints/last.ckpt

n_repeat: 5

datamodule: # overriding default context_class_size
  context_class_size: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 25, 30, 35, 40, 45, 50]


defaults:
  - datamodule: waterbirds_emb_contexts # Options: 'inaturalist_emb_contexts', 'waterbirds_emb_contexts', 'cub_emb_contexts', 'imagenet_emb_contexts'
  - model: incontext_learner_gptj_v2
  - trainer: default
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/runs/${name}/${aim_hash}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True
