name: extract_encodings
seed: 0
print_config: True
ignore_warnings: False


defaults:
  - datamodule: inaturalist2017
  - encoding_extractor: dinov2_vitb14
  - override hydra/job_logging: custom
  - _self_

device: cuda:0 # The device to be used for computation.
save_path: ${oc.env:DATA_ROOD_DIR}/${datamodule.name}/${encoding_extractor.name} # The path where the extracted encodings will be saved.

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/runs/${name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True