name: generate_and_save_val_sets
seed: 0
print_config: True
ignore_warnings: False

spurious_setting: sum # Set to fulfill datamodule requirements; actual value irrelevant for this script.

defaults:
  - datamodule: inaturalist_emb_contexts
  - override hydra/job_logging: custom
  - _self_

are_spurious_tokens_fixed: ${datamodule.are_spurious_tokens_fixed}
are_class_tokens_fixed: ${datamodule.are_class_tokens_fixed}
dataset_path: ${datamodule.dataset_path}
encoding_extractor: ${datamodule.encoding_extractor}
context_class_size: ${datamodule.context_class_size}
minority_group_proportion: ${datamodule.minority_group_proportion}

save_path: ${dataset_path}/context_val_sets_${context_class_size}_${minority_group_proportion}/${encoding_extractor}

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/runs/${name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True