experiment_name: ???
n_repeat: 1
gpu_device: 0

global_lr: 1e-5

defaults:
  - experiment_settings: pipeline
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/runs/${experiment_name}
  job:
    chdir: True