name: train
seed: 0
print_config: True
ignore_warnings: False


spurious_setting: sum # Options: 'no_spurious'(x), 'sum'(x+c), 'separate_token'(x, c) , 'sum_with_spurious'(x+c, c)

v1_behavior: False

defaults:
  - datamodule: inaturalist_emb_contexts
  - model: incontext_learner_gptj_v2
  - optimizer: adam_w
  - scheduler: warmup_cosine_annealing
  - trainer: default
  - loggers: [aim]
  - callbacks: [lr_monitor, model_checkpoint]
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/runs/${name}/${now:%Y-%m-%d_%H-%M-%S} # IMPORTANT: Directory name AUTO-UPDATED with 'aim' logger's HASH when 'aim' is ENABLED
  job:
    chdir: True
