name: train
seed: 0
print_config: True
ignore_warnings: False


spurious_setting: wb_dro # Options: wb_erm, wb_dro, inat_no_spurious, inat_sum_erm, inat_sum_dro
sp_token_generation_mode: opposite  # Options: opposite and random

v1_behavior: False

defaults:
  - datamodule: waterbirds_emb_contexts  # Options: inaturalist_emb_contexts, waterbirds_emb_contexts
  - model: incontext_learner_gptj_80m
  - optimizer: adam
  - scheduler: warmup_cosine_annealing
  - trainer: default
  - loggers: [aim]
  - callbacks: [lr_monitor, model_checkpoint]
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/runs/${name}/${now:%Y-%m-%d_%H-%M-%S} # IMPORTANT: Directory name AUTO-UPDATED with 'aim' logger's HASH when 'aim' is ENABLED
  job:
    chdir: True
