experiment_name: DINO_wb_random_train_val
accelerator: "gpu"
gpu_device: [0]

model_path: ${oc.env:OUTPUT_DIR}/runs/${experiment_name}/checkpoints/best_checkpoint.ckpt
data_path: ${oc.env:OUTPUT_DIR}/cache/embedding_extractor/waterbirds/dinov2_vits14

datamodule:
  batch_size: 64
  num_workers: 8

defaults:  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled
  - _self_ 
  
hydra:  
  output_subdir: null  
  run:
    dir: ${oc.env:OUTPUT_DIR}/runs/${experiment_name}
