_target_: src.datamodules.INaturalist2017DataModule
name: inaturalist2017

dataset_path: ${oc.env:DATA_ROOT_DIR}/inaturalist2017
min_images_per_category: 500
resize_size: 256
crop_size: 224
batch_size: 32
num_workers: 4

fully_outer_supercategories: [Amphibia, Mammalia]
fully_inner_supercategories: [Animalia, Arachnida, Mollusca] # they have only one category
outer_classes_size: 0.1
inner_val_size: 0.2
