_target_: src.datamodules.INaturalistEmbContextsDataModule
name: inaturalist_emb_contexts

context_class_size: 50
minority_group_proportion: 0.1

dataset_path: ${oc.env:DATA_ROOD_DIR}/inaturalist2017
encoding_extractor: dinov2_vitb14
saved_val_sets_path: ${datamodule.dataset_path}/context_val_sets_${datamodule.context_class_size}_${datamodule.minority_group_proportion}/${datamodule.encoding_extractor}

inner_train_len: ${trainer.max_steps}
inner_val_len: 1024 # 2^n, because CombinedDataloader removes the last non-full batch
outer_val_len: 1024 # 2^n, because CombinedDataloader removes the last non-full batch
inner_outer_val_len: 1024 # 2^n, because CombinedDataloader removes the last non-full batch

are_spurious_tokens_fixed: False
are_class_tokens_fixed: True
token_generation_mode: opposite  # c,-c  y,-y

batch_size: 32
num_workers: 4

spurious_setting: ${spurious_setting}  # Use the global value of 'spurious_setting'