_target_: src.datamodules.INaturalistEmbContextsDataModuleV2
name: inaturalist_emb_contexts

context_class_size: 50
minority_group_proportion: 0.1

dataset_path: ${oc.env:DATA_ROOT_DIR}/inaturalist2017
encoding_extractor: dinov2_vitb14
saved_val_sets_path: ${datamodule.dataset_path}/context_val_sets_${datamodule.context_class_size}_${datamodule.minority_group_proportion}/${datamodule.encoding_extractor}

train_len: ${trainer.max_steps}
eval_len: 1024 # 2^n, because CombinedDataloader removes the last non-full batch

batch_size: 32
num_workers: 4

spurious_setting: ${spurious_setting}  # Use the global value of 'spurious_setting'
sp_token_generation_mode: ${sp_token_generation_mode}  # Use the global value of 'sp_token_generation_mode'

v1_behavior: ${v1_behavior}

rotate_encodings: False
n_rotation_matrices: 1000  # 1000 works well, but is slow. Reduce for efficiency when experimenting

label_noise_ratio_interval: null  # [min_ratio, max_ratio], the label noise ratio is uniformly sampled from this interval
input_noise_std_interval: null  # [min_std, max_std], the standard deviation of the Gaussian noise will be uniformly sampled from this interval
permute_input_dim: False

ask_context_prob: null

val_sets: [inner, inner_outer, outer]  # the order here should match the order in the combined loader
