_target_: src.datamodules.WaterbirdsEmbContextsDataModule
name: waterbirds_emb_contexts

context_class_size: 50 # equivalent to context_size = 100 (context_size = 2 * context_class_size)
group_proportions: random # random or [0.45, 0.05, 0.05, 0.45]

root_dir: ${oc.env:DATA_ROOT_DIR}
encoding_extractor: dinov2_vitb14

data_length: ${trainer.max_steps} # this is used for training

avg_norms_and_encodings: waterbirds # inaturalist2017, waterbirds

are_spurious_tokens_fixed: False
are_class_tokens_fixed: True
token_generation_mode: opposite  # c,-c  y,-y

batch_size: 32
num_workers: 4

spurious_setting: ${spurious_setting}  # Use the global value of 'spurious_setting'

eval_query_split: test # split the queries in evaluation mode

randomly_swap_labels: False # to randomly change the labels during training 0 <-> 1
randomly_change_task: False # to randomly change the task during training to predict the background

rotate_encodings: False # to randomly rotate the encodings during training
n_rotation_matrices: null # count of the rotation matrices to use
class_dependant_rotate: False # set to True to rotate each class independently

val_sets: null # null if there is a single val set, otherwise this is the list of names of val sets